In [3]:
# MATH0001 Data Prepocessing
# 1. getting started-- install the libraries and import the required libraries
!pip install scikit-learn pandas numpy

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.impute import SimpleImputer


In [7]:
## Data Preprocessing steps:
'''
1. Handling missing data
2. Encoding categorical data
3. Splitting the dataset into training and test sets
4. Feature scaling

In this session, we will go through each steps
'''
# 2.1 Handling missing data
# Import the dataset from Data.csv in the working directory
dataset = pd.read_csv("Data.csv")

# Print the full dataset to inspect raw values and identify missing entries
dataset

,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,NaN,Yes
5,France,35.0,58000.0,Yes
6,Spain,NaN,52000.0,No
7,France,48.0,79000.0,Yes
8,Germany,50.0,83000.0,No
9,France,37.0,67000.0,Yes


In [8]:
# As we can see, missing values (denoted NA) exist in both the Age and Salary columns
# We resolve these missing values by imputing each missing entry with the column’s average value calculated from all non-missing observations.


dataset['Age'] = dataset['Age'].fillna(dataset['Age'].mean())
dataset['Salary'] = dataset['Salary'].fillna(dataset['Salary'].mean())

In [10]:
# Extension: How does to compute mean of a dataset when there is missing values
x=np.array([1.0,2.0,3.0])
x[0] = np.nan #treat x[0] as the missing data

print(f'The result of mean of x (not ignoring missing data):{np.mean(x)}') # nan (not a number)

#use np.nanmean() to ignore the missing values and compute the mean
print(f'The result of mean of x(ignore the missing data):{np.nanmean(x)}') # 2.5


The result of mean of x (not ignoring missing data):nan
The result of mean of x(ignore the missing data):2.5


In [11]:
# Now we can see the cleaned dataset after missing value imputation
dataset

,Country,Age,Salary,Purchased
0,France,44.000000,72000.000000,No
1,Spain,27.000000,48000.000000,Yes
2,Germany,30.000000,54000.000000,No
3,Spain,38.000000,61000.000000,No
4,Germany,40.000000,63777.777778,Yes
5,France,35.000000,58000.000000,Yes
6,Spain,38.777778,52000.000000,No
7,France,48.000000,79000.000000,Yes
8,Germany,50.000000,83000.000000,No
9,France,37.000000,67000.000000,Yes


In [29]:
# 2.2 Encoding the categorical data


# Since some text columns do not require factor encoding. The code below manually converts selected columns into factor variables with numerical label encoding for machine learning.
# Define all unique country levels and map each to integer codes: France=1, Spain=2, Germany=3
# direct mapping
country_mapping = {'France':1,'Spain':2,'Germany':3}
dataset['Country_LabelEncoder'] = dataset['Country'].map(country_mapping)
print(dataset)






   Country        Age        Salary Purchased  Country_LabelEncoder  \
0   France  44.000000  72000.000000        No                     1   
1    Spain  27.000000  48000.000000       Yes                     2   
2  Germany  30.000000  54000.000000        No                     3   
3    Spain  38.000000  61000.000000        No                     2   
4  Germany  40.000000  63777.777778       Yes                     3   
5   France  35.000000  58000.000000       Yes                     1   
6    Spain  38.777778  52000.000000        No                     2   
7   France  48.000000  79000.000000       Yes                     1   
8  Germany  50.000000  83000.000000        No                     3   
9   France  37.000000  67000.000000       Yes                     1   

   Purchased_LabelEncoder  
0                       0  
1                       1  
2                       0  
3                       0  
4                       1  
5                       1  
6                     

In [30]:
# Convert Purchased Yes/No responses into binary factor labels: No=0, Yes=1

#Method 1
purchased_mapping = {'No': 0, 'Yes': 1}
dataset['Purchased_LabelEncoder'] = dataset['Purchased'].map(purchased_mapping)
print(dataset)



   Country        Age        Salary Purchased  Country_LabelEncoder  \
0   France  44.000000  72000.000000        No                     1   
1    Spain  27.000000  48000.000000       Yes                     2   
2  Germany  30.000000  54000.000000        No                     3   
3    Spain  38.000000  61000.000000        No                     2   
4  Germany  40.000000  63777.777778       Yes                     3   
5   France  35.000000  58000.000000       Yes                     1   
6    Spain  38.777778  52000.000000        No                     2   
7   France  48.000000  79000.000000       Yes                     1   
8  Germany  50.000000  83000.000000        No                     3   
9   France  37.000000  67000.000000       Yes                     1   

   Purchased_LabelEncoder  
0                       0  
1                       1  
2                       0  
3                       0  
4                       1  
5                       1  
6                     

In [31]:
# 2.3 Splitting the dataset into training and test sets
# In python, we use "train_test_split" in "sklearn.model_selection" to split two types of datasets

# set the random state to ensure identical train/test split results every time the code runs;
RANDOM_STATE = 123 # Do NOT modify this line

X = dataset[['Country_LabelEncoder', 'Age', 'Salary']].values #feature matrix, all rows and all columns except the last column
Y = dataset['Purchased_LabelEncoder'].values # target vector, all rows and  the last column

X_train,X_test,Y_train,Y_test = train_test_split(
    X, # feature matrix
    Y, # target vector
    test_size =0.2, # 20% of the dataset are test_dataset
    random_state = RANDOM_STATE,
    stratify = Y # enable Stratified Sampling, ensures the ratio of 'Purchased' is the same in train set and test set
)

print("Split result\n")
print(f"Original dataset length: {len(dataset)} ")
print(f"training set length: {len(X_train)} rows, ({len(X_train)/len(dataset)*100:.1f}%)")
print(f"testing set length: {len(X_test)} rows, ({len(X_test)/len(dataset)*100:.1f}%)")

print("\ntarget distribution in training set：")
print(pd.Series(Y_train).value_counts())

print("\ntarget distribution in testint set：")
print(pd.Series(Y_test).value_counts())



Split result

Original dataset length: 10 
training set length: 8 rows, (80.0%)
testing set length: 2 rows, (20.0%)

target distribution in training set：
1    4
0    4
Name: count, dtype: int64

target distribution in testint set：
0    1
1    1
Name: count, dtype: int64


In [33]:
## 2.4 feature Scaling
# We use "StandardScaler" in "sklearn.preprocessing" to realize this process

# Attention: We should do feature Scaling after spliting training & testing dataset
#            We can only use data from training set to fit scaler, in order to avoid data leaking

scaler = StandardScaler()

columns_to_scale = [1,2] # Age (column 1) 7 Salary (column 2)

#make a copy to avoid modifying the original data
X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

X_train_scaled[:,columns_to_scale] = scaler.fit_transform(X_train[:, columns_to_scale])
# Attention: use "tranform", BUT NOT "fit_tranform" to use trained scaler to tranform testing set
X_test_scaled[:, columns_to_scale] = scaler.transform(X_test[:, columns_to_scale])

print(X_train_scaled)
print(X_test_scaled)
print('\n\n')
# transfer the training & testing set back to dataframe to output more cleanly
training_set = pd.DataFrame(
    X_train_scaled,
    columns=['Country', 'Age', 'Salary']
)
training_set['Purchased'] = Y_train

test_set = pd.DataFrame(
    X_test_scaled,
    columns=['Country', 'Age', 'Salary']
)
test_set['Purchased'] = Y_test

training_set['Country'] = training_set['Country'].astype(int) # transfer back to int type
test_set['Country'] = test_set['Country'].astype(int) # transfer back to int type

print(training_set)
print('\n\n')
print(test_set)

[[ 2.         -1.52702226 -1.31942127]
 [ 1.          0.68752187  0.64436853]
 [ 3.          1.46912568  1.54443885]
 [ 1.         -0.22434924  0.23524565]
 [ 3.         -1.13622036 -0.82847382]
 [ 1.          1.20859108  1.21714055]
 [ 1.         -0.48488385 -0.50117552]
 [ 2.          0.00723707 -0.99212297]]
[[ 2.         -0.09408194 -0.2557018 ]
 [ 3.          0.16645266 -0.02841131]]



   Country       Age    Salary  Purchased
0        2 -1.527022 -1.319421          1
1        1  0.687522  0.644369          0
2        3  1.469126  1.544439          0
3        1 -0.224349  0.235246          1
4        3 -1.136220 -0.828474          0
5        1  1.208591  1.217141          1
6        1 -0.484884 -0.501176          1
7        2  0.007237 -0.992123          0



   Country       Age    Salary  Purchased
0        2 -0.094082 -0.255702          0
1        3  0.166453 -0.028411          1
